"""Generate docs/DATA_DICTIONARY.md from the live warehouse (types, examples, observed allowed values).

Descriptions are written by hand in DESCRIPTIONS; the generator fails if a column has no description,
so the dictionary can never silently drift from the schema.  Usage: python -m pipeline.docgen
"""
import sqlite3
from pathlib import Path

from .load import DB_PATH

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "DATA_DICTIONARY.md"

DESCRIPTIONS = {
    "dim_brand": {
        "brand_key": "Surrogate key (assigned alphabetically by brand name).",
        "brand_name": "Brand name.",
        "code_prefix": "Two-letter prefix used in factory_code for this brand.",
    },
    "dim_year": {"year_key": "Calendar year the factory record refers to (natural key)."},
    "dim_country": {
        "country_key": "Surrogate key (assigned alphabetically by country name).",
        "country_name": "Country as written in the source data.",
        "iso2": "ISO-3166 alpha-2 code, taken from the country segment of factory_code.",
        "region": "Analyst-defined grouping of countries into regions (not in the source data).",
    },
    "dim_location": {
        "location_key": "Surrogate key for a (country, city) pair.",
        "country_key": "FK to dim_country.",
        "city": "City of the factory.",
        "latitude": "Latitude in decimal degrees as stored in the source CSV.",
        "longitude": "Longitude in decimal degrees as stored in the source CSV.",
    },
    "dim_factory": {
        "factory_key": "Surrogate key (assigned in factory_code order).",
        "source_factory_id": "factory_id from the source CSV (kept for lineage).",
        "factory_code": "Human-readable factory identifier: brand prefix - country code - sequence.",
        "brand_key": "FK to dim_brand.",
        "location_key": "FK to dim_location.",
    },
    "fact_factory_snapshot": {
        "factory_key": "PK and FK to dim_factory; one fact row per factory.",
        "brand_key": "FK to dim_brand (denormalised from dim_factory for simpler joins).",
        "location_key": "FK to dim_location (denormalised from dim_factory).",
        "country_key": "FK to dim_country (denormalised via dim_location).",
        "year_key": "FK to dim_year; the single year the source record carries.",
        "workers": "Total headcount of the factory.",
        "monthly_output": "Units produced per month.",
        "production_cost_index": "Source `production_cost`: a normalised cost index (USD), not an absolute cost.",
        "output_per_worker": "Derived: monthly_output / workers, rounded to 2 dp.",
        "cost_index_per_million_units": "Derived: production_cost_index / monthly_output x 1,000,000, rounded to 2 dp.",
        "size_tier": "Derived from workers: Large >= 25,000; Medium 10,000-24,999; Small < 10,000.",
        "cost_band": "Derived from production_cost_index: High >= 50; Medium 40-49.99; Low < 40.",
    },
    "vw_factory_flat": {
        "factory_key": "See fact_factory_snapshot.", "factory_code": "See dim_factory.",
        "brand": "dim_brand.brand_name.", "country": "dim_country.country_name.",
        "region": "dim_country.region.", "city": "dim_location.city.",
        "latitude": "dim_location.latitude.", "longitude": "dim_location.longitude.",
        "year": "fact_factory_snapshot.year_key.", "workers": "See fact_factory_snapshot.",
        "monthly_output": "See fact_factory_snapshot.", "production_cost_index": "See fact_factory_snapshot.",
        "output_per_worker": "See fact_factory_snapshot.", "cost_index_per_million_units": "See fact_factory_snapshot.",
        "size_tier": "See fact_factory_snapshot.", "cost_band": "See fact_factory_snapshot.",
    },
}
TABLE_ORDER = ["dim_brand", "dim_year", "dim_country", "dim_location", "dim_factory",
               "fact_factory_snapshot", "vw_factory_flat"]
TABLE_NOTES = {
    "vw_factory_flat": "View joining the fact and all dimensions; used by the analysis queries.",
}


def _fmt(x) -> str:
    return f"{x:.4f}".rstrip("0").rstrip(".") if isinstance(x, float) else str(x)


def _allowed(con, table, col, ctype, is_key) -> str:
    n_distinct, n_rows = con.execute(f'SELECT COUNT(DISTINCT "{col}"), COUNT(*) FROM "{table}"').fetchone()
    if ctype == "TEXT":
        if n_distinct <= 12:
            return ", ".join(str(r[0]) for r in con.execute(f'SELECT DISTINCT "{col}" FROM "{table}" ORDER BY 1'))
        return "unique" if n_distinct == n_rows else f"{n_distinct} distinct values"
    if is_key:
        return "unique"
    lo, hi = con.execute(f'SELECT MIN("{col}"), MAX("{col}") FROM "{table}"').fetchone()
    return f"{_fmt(lo)} to {_fmt(hi)}"


def build(db_path: Path = DB_PATH) -> str:
    con = sqlite3.connect(db_path)
    lines = ["# Data Dictionary", "",
             "_Generated by `python -m pipeline.docgen` from `warehouse.db`; types come from the SQLite schema, "
             "examples and allowed values are observed in the data._", "",
             "Provenance: the source CSV is described in the README as constructed for analytical purposes "
             "from publicly available information about manufacturing locations. Treat values as illustrative.", ""]
    for table in TABLE_ORDER:
        info = con.execute(f'PRAGMA table_info("{table}")').fetchall()  # cid,name,type,notnull,default,pk
        missing = [c[1] for c in info if c[1] not in DESCRIPTIONS[table]]
        if missing:
            raise KeyError(f"No description for {table}: {missing}")
        n = con.execute(f'SELECT COUNT(*) FROM "{table}"').fetchone()[0]
        lines += [f"## `{table}` ({n} rows)", ""]
        if table in TABLE_NOTES:
            lines += [TABLE_NOTES[table], ""]
        lines += ["| Column | Type | Key | Description | Example | Allowed / observed values |", "|---|---|---|---|---|---|"]
        fks = {r[3]: f"{r[2]}.{r[4]}" for r in con.execute(f'PRAGMA foreign_key_list("{table}")')}
        for _, name, ctype, _nn, _d, pk in info:
            key = "PK" if pk else ""
            if name in fks:
                key = (key + ", " if key else "") + f"FK -> {fks[name]}"
            example = con.execute(f'SELECT "{name}" FROM "{table}" LIMIT 1 OFFSET {n // 2}').fetchone()[0]
            lines.append(f"| `{name}` | {ctype or 'derived'} | {key} | {DESCRIPTIONS[table][name]} | "
                         f"`{example}` | {_allowed(con, table, name, ctype or 'TEXT', bool(pk))} |")
        lines.append("")
    con.close()
    return "\n".join(lines)


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(build(), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
